### ISSUE TITLE
Changelog für v0.38 nicht vergessen

### ISSUE THREAD

**Issue by LeSpocky** [FreifunkMD/site-ffmd#102]
Vor dem finalen v0.38 Release bitte noch das Changelog in `README.md` auf den aktuellen Stand bringen!

**Comment by penguineer** [comment]
Reopened due to
* https://github.com/FreifunkMD/site-ffmd/pull/105#issuecomment-381871193
* https://github.com/FreifunkMD/site-ffmd/pull/105#issuecomment-381888599

Which is:

Three commits which are not mentioned in the changelog:
* ea7dbd8d0c6e8920031b814b224c711dc54c2789
* 1b2ef311f08caeb341bd20360d46b72fb157cf93
* 43c85f7f2e649e072f567bcfc5dc72b81a1566f1

And some questions about the changelog:
* Who is the target audience for the changelog?
* On the other hand: If we specify the target gluon version, why link all the intermediate changelogs?

**Comment by penguineer** [comment]
Ggf. ein Thema für Freitag?

**Comment by penguineer** [comment]
IMHO tun wir uns auch einen Gefallen, wenn wir fordern, dass:
a) PR, die für das Changelog relevante Inhalte mitbringen, dieses auch gleich in das Changelog einfügen oder
b) wir eine Liste mit Items führen, die in das Changelog aufgenommen werden müssen.

Anderenfalls muss man beim Erstellen des Changelogs noch einmal alle Änderungen durchgehen, ggf. Diskussionen führen etc. Was dann der Reviewer für die Feststellung der Vollständigkeit _noch einmal_ tun muss. Das lässt sich bestimmt besser gestalten.
